name: Bot CIMAC 24/7
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests beautifulsoup4
      - run: python bot.py
        env:
          GREEN_TOKEN: ${{ secrets.GREEN_TOKEN }}
          CIMAC_USER: ${{ secrets.CIMAC_USER }}
          CIMAC_PASS: ${{ secrets.CIMAC_PASS }}
